apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-secret
  namespace: dev
type: Opaque
stringData:
  jenkins-admin-user: admin
  jenkins-admin-password: change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-github-ssh
  namespace: dev
type: Opaque
stringData:
  private-key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    replace-with-your-github-ssh-private-key
    -----END OPENSSH PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-dockerhub
  namespace: dev
type: Opaque
stringData:
  username: spotifyyyyy
  password: replace-with-dockerhub-access-token
