replicaCount: 1

image:
  repository: docker.io/spotifyyyyy/chat-server
  tag: 1eac7f26d08d
  pullPolicy: Always

imagePullSecrets: []

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: backend.kube.com
      paths:
        - path: /api
          pathType: Prefix
        - path: /ws/chat
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

spring:
  profile: prod

frontend:
  url: http://frontend.kube.com

database:
  url: jdbc:postgresql://postgresql.dev.svc.cluster.local:5432/chatdb
  username: chat
  ddlAuto: validate
  flywayEnabled: true
  flywayBaselineOnMigrate: true

redis:
  host: redis-master.dev.svc.cluster.local
  port: 6379
  username: default

kafka:
  bootstrapServers: kafka.dev.svc.cluster.local:9092
  topics:
    chatMessageCreated: chat.message.created
    chatRoomRead: chat.room.read
    chatDlq: chat.dlq
  consumer:
    maxRetryCount: 3
    retryBackoffMs: 1000

outbox:
  relay:
    fixedDelayMs: 1000
    batchSize: 100
    maxRetryCount: 10

observability:
  springdocApiDocsEnabled: true
  springdocSwaggerUiEnabled: true
  logRootLevel: info
  logSpringLevel: info
  logAppLevel: debug

secret:
  create: true
  name: ""
  env:
    DB_PASSWORD: chat1234
    REDIS_PASSWORD: ""
    JWT_SECRET: T+FITVBc8qEi9tZ/TgN7mfZ9wb0BqArbh4B+RMZ9zKU=
    AUTH_COOKIE_SECURE: "false"

truststore:
  enabled: false
  secretName: kafka-truststore
  mountPath: /app/config
  fileName: kafka.truststore.jks
