replicaCount: 1

image:
  repository: docker.io/spotifyyyyy/chat-frontend
  tag: a17781619808
  pullPolicy: Always

imagePullSecrets: []

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: frontend.kube.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kube-com-tls
      hosts:
        - frontend.kube.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

backend:
  apiUrl: https://backend.kube.com/api
  wsUrl: wss://backend.kube.com/ws/chat

frontend:
  debug: true
