apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.configMapName" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  APP_API_URL: {{ .Values.backend.apiUrl | quote }}
  APP_WS_URL: {{ .Values.backend.wsUrl | quote }}
  APP_DEBUG: {{ .Values.frontend.debug | quote }}
