replicaCount: 1

image:
  repository: docker.io/spotifyyyyy/chat-server
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

containerPort: 8080

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: backend.kube.com
      paths:
        - path: /api
          pathType: Prefix
        - path: /ws/chat
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

livenessProbe:
  enabled: true
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 6

readinessProbe:
  enabled: true
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 6

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

spring:
  profile: prod

frontend:
  url: https://frontend.kube.com

database:
  url: jdbc:postgresql://postgresql.default.svc.cluster.local:5432/chatdb
  username: chat
  ddlAuto: validate
  flywayEnabled: true
  flywayBaselineOnMigrate: true

redis:
  host: redis.default.svc.cluster.local
  port: 6379
  username: default

kafka:
  bootstrapServers: kafka.default.svc.cluster.local:9092
  topics:
    chatMessageCreated: chat.message.created
    chatRoomRead: chat.room.read
    chatDlq: chat.dlq
  consumer:
    maxRetryCount: 3
    retryBackoffMs: 1000

outbox:
  relay:
    fixedDelayMs: 1000
    batchSize: 100
    maxRetryCount: 10

observability:
  springdocApiDocsEnabled: false
  springdocSwaggerUiEnabled: false
  logRootLevel: info
  logSpringLevel: info
  logAppLevel: info

secret:
  create: true
  name: ""
  env:
    DB_PASSWORD: change-me
    REDIS_PASSWORD: change-me
    JWT_SECRET: change-me
    KAFKA_PASSWORD: change-me
    KAFKA_TRUSTSTORE_PASSWORD: change-me

truststore:
  enabled: true
  secretName: kafka-truststore
  mountPath: /app/config
  fileName: kafka.truststore.jks
