apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/xcdev-0/chat-platform-infra.git
    targetRevision: main
    path: infra-shared/helm/frontend
    helm:
      releaseName: frontend
      valueFiles:
        - ../../../infra-aws/environments/dev/apps/frontend-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
