apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: mysql
      targetRevision: 14.0.3
      helm:
        releaseName: mysql
        valueFiles:
          - $values/infra-aws/environments/dev/data/mysql-values.yaml
    - repoURL: https://github.com/xcdev-0/chat-platform-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
